### PR TITLE
Add spec for SQL::Generator::Emitter::Literal::String#dispatch

### PR DESCRIPTION
**Pull request by dkubb**
For some reason this is not killing the mutations in the method. I can't even tell if mutant is even executing the spec, but based on some preliminary debugging it doesn't seem to be finding it.

 I am adding this spec into a branch for @mbj to review.

### CODE REVIEW

**Comment by dkubb** [comment]
@mbj do you know why mutant isn't running this spec and killing the mutations in the method?

Also, wdyt about moving out the specs from the gigantic emitter spec into per-emitter specs like this? It'll allow us to kill mutations earlier, rather than waiting until the very end. I've done that a few times, and it's more painful than when I got the code to pass under mutant early and just kept it there.

**Comment by solnic** [comment]
@dkubb `#dispatch` is a private method

**Comment by dkubb** [comment]
@solnic I know. There's some precedence in other projects that use mutant to use this naming convention.

In the end the test probably won't be named _for_ dispatch directly, but some public instance method in the class that uses dispatch. I only named it dispatch because mutant isn't supposed to care what the name of the spec is.. for a private method it's supposed to run all the specs in the directory regardless of their name, but it doesn't seem to be running it in this case.

**Comment by solnic** [comment]
@dkubb I think the fact it is a private method and the spec file is named by it makes mutant confused (just guessing here though)

**Comment by dkubb** [comment]
@solnic yeah, that could be it. Although I did try making it public just to see, and it still didn't run the spec, that's why I was asking @mbj for help.

**Comment by mbj** [comment]
@dkubb All Emitter `#dispatch` methods should get speced via a public interface. The problem: Mutant (0.2) does not support kill delegation to a common public interface. I solve this via symlinks currently. I hope to have the time to improve this shorty.

I 'd sugest we use `mutant --rspec-full` in the meantime. Or create lots of symlinks...

**Comment by solnic** [comment]
@mbj I'm fine with --rspec-full. it's better to have mutant running slower than writing specs that make no sense. Our libs are small so it shouldn't take too long to run all mutations anyway.

**Comment by mbj** [comment]
@solnic Unparser runs **ages** with `--rspec-full`. I hope to support kill configuration soon. Maybe I'll try a bountysource campaing also ;)

**Comment by mbj** [comment]
See here how mutant rake task can be overriden: https://github.com/mbj/unparser/blob/master/Rakefile#L4-L24

**Comment by solnic** [comment]
@mbj it's better to have it run ages than waste time on specs that add clutter to the test suite and make it hard to change and maintain.

**Comment by mbj** [comment]
@solnic Yeah.

**Comment by dkubb** [comment]
Another approach, and I realize this is a big change, would be to run the specs once and track which specs (or ideally individual examples) cover which lines of code. Then when we mutate a pice of code we can run just the examples that relate to it. This would simplify configuration and would work OOTB for more projects.

**Comment by solnic** [comment]
That would be perfect...otherwise maintaining mutant configuration could become a PITA (in the long term) :/

**Comment by dkubb** [comment]
Using this "tracking" approach would be nice for other things. When a constant is used in a method, we could add that to the list of lines covered by a spec too. Then when we start to run mutations we could mutate the constant assignments, which would be awesome.

**Comment by mbj** [comment]
@dkubb I'd love to support this, but I don not see a chance to do this with rspec2. Maybe we can reimplement the subset of the rspec syntax in a more reflectable test tool. There we could also map a specific mutation to a specific expectation/assertion that killed the mutation. Not only the example.

That constant covering via backtracking will also be really complex. To find at which location a specific constant is defined needs a **full** implementation of the constant scoping/assignment rules within mutant. We can use RBX to reflect on the constant scope, but this would result in an RBX-only feature.

Sure the trivial cases are easy, but I dislike to ship a tool that produces false positives.

**Comment by solnic** [comment]
OK so the simplest thing that can possibly work is to run all unit tests. That's OK given the size of our test suites. It takes 20 seconds to run --rspec-full against SQL specs.

**Comment by dkubb** [comment]
I'm going to close this PR since there hasn't been any further discussion on it within a week.

**Pull request closed without merging**
